/* Generated by cbindgen — do not edit manually. */

#ifndef CBCL_H
#define CBCL_H

/* Warning: this file is autogenously generated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to a CBCL agent. Created with `cbcl_agent_new`, freed with `cbcl_agent_free`.
 */
typedef struct CbclAgent CbclAgent;

/**
 * FFI result: contains either a success string or an error string.
 *
 * The caller must free `data` with `cbcl_string_free` when done.
 * If `error` is 0, `data` is the success value.
 * If `error` is non-zero, `data` is the error message.
 */
typedef struct CbclResult {
  /**
   * Null-terminated UTF-8 string (must be freed with `cbcl_string_free`).
   * NULL if allocation failed.
   */
  char *data;
  /**
   * 0 on success, non-zero on error.
   */
  int32_t error;
} CbclResult;

/**
 * Parse an S-expression string into a CBCL message.
 *
 * Returns the canonical serialized form on success.
 * The caller must free the result with `cbcl_string_free`.
 *
 * # Safety
 *
 * `input` must be a valid null-terminated UTF-8 C string.
 */
struct CbclResult cbcl_parse_message(const char *input);

/**
 * Parse and verify a dialect definition against R1/R2/R3 rules.
 *
 * Returns "ok" on success or an error description.
 * The caller must free the result with `cbcl_string_free`.
 *
 * # Safety
 *
 * `input` must be a valid null-terminated UTF-8 C string.
 */
struct CbclResult cbcl_verify_dialect(const char *input);

/**
 * Create a new CBCL agent with the given ID and base dialect installed.
 *
 * Returns an opaque handle. The caller must free it with `cbcl_agent_free`.
 * Returns NULL on error (e.g. null or invalid UTF-8 id).
 *
 * # Safety
 *
 * `id` must be a valid null-terminated UTF-8 C string.
 */
struct CbclAgent *cbcl_agent_new(const char *id);

/**
 * Send a tell message from the agent to a recipient.
 *
 * Evaluates the message against the agent's dialect registry and returns the
 * expanded effect form. The caller must free the result with `cbcl_string_free`.
 *
 * # Safety
 *
 * - `agent` must be a valid pointer from `cbcl_agent_new`.
 * - `recipient` and `content` must be valid null-terminated UTF-8 C strings.
 */
struct CbclResult cbcl_agent_send(struct CbclAgent *agent,
                                  const char *recipient,
                                  const char *content);

/**
 * Free an agent handle created by `cbcl_agent_new`.
 *
 * # Safety
 *
 * `agent` must be a valid pointer from `cbcl_agent_new`, or NULL (which is a no-op).
 * After calling this function, the pointer must not be used again.
 */
void cbcl_agent_free(struct CbclAgent *agent);

/**
 * Free a string returned by any `cbcl_*` function.
 *
 * # Safety
 *
 * `s` must be a pointer returned by a `cbcl_*` function's `data` field,
 * or NULL (which is a no-op). After calling this function, the pointer
 * must not be used again.
 */
void cbcl_string_free(char *s);

#endif  /* CBCL_H */
